spring:
  boot:
    message: Deparment Service Configuration Files updated.
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
